version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: meseum_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: me_seum
      POSTGRES_USER: meseum_user
      POSTGRES_PASSWORD: NathanGalung_SQL_1965
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U meseum_user -d me_seum"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: meseum_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres

volumes:
  postgres_data:
    driver: local